### ISSUE TITLE
Windows 7 command ".." not found

### ISSUE THREAD

**Issue by klamadotuk** [micooz/wallpaper#1]
If I call wallpaper.set(...) on Windows 7, an error occurs ('the command ".." could not be found'). Changing the command to '..\bridge\wallpaper.exe', instead of '../bridge/wallpaper.exe' works. I'm on node 5.7.0. Tried this with cygwin and cmd.exe.

Does this work for you on Windows?

**Comment by micooz** [comment]
I tested it on Windows8.1 few months ago and it worked well, but unfortunately I haven't make depth tests on other versions of Windows.

I think it's a path rule problem among Windows and other platforms. I will be very grateful if you send me PRs. :smiley:

**Comment by micooz** [comment]
It should work now, thanks again for your contribution.
BTW, I haven't test it on Linux, If you encountered problems, tell me.
